specVersion: 0.2.0
name: astarsts-dappstaking-data
version: 0.0.4
description: This SubQuery project can be use as a starting point for Astar network
repository: https://github.com/AstarStats/astarsts-dappstaking-data
schema:
  file: ./schema.graphql
network:
  endpoint: wss://astar.api.onfinality.io/public-ws
  genesisHash: "0x9eb76c5184c4ab8679d2d5d819fdf90b9c001403e9e17da2e14b6d8aec4029c6"
  dictionary: https://api.subquery.network/sq/subquery/astar-dictionary
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 814289
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleDappStakingReward
          kind: substrate/EventHandler
          filter:
            module: dappsStaking
            method: Reward
        - handler: handleBondAndStake
          kind: substrate/EventHandler
          filter:
            module: dappsStaking
            method: BondAndStake
        - handler: handleUnbondAndUnstake
          kind: substrate/EventHandler
          filter:
            module: dappsStaking
            method: UnbondAndUnstake
